server:
  port: 9001

spring.mail.host: smtp.qq.com
spring.mail.username: liliangbin1520@qq.com
spring.mail.password: nxlphkingmxhecge
spring.mail.default-encoding: UTF-8
spring.mail.port: 465
spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.debug: true


user:
  name: 2286824491@qq.com

spring.application.name: spirng-boot-rabbitmq

spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: admin
spring.rabbitmq.password: 123456